var express = require('express');
var path = require('path');
var logger =require('morgan');
var bodyParser = require('body-parser');
var app = express();
var routes = require('./routes');
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'ejs');
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended: false}));
app.use(express.static(path.join(__dirname, 'public')));
app.use('/users', routes);
app.listen(3000);
console.log('Server started at port 3000');
module.exports = app;